name = "weddingflare-api-dev"

# Build Configuration
type = "javascript"
compatibility_date = "2021-10-04"

# Account Settings
account_id = "257d9994d1e15e8fbeb6053f590ad96b"
zone_id = "60e63062a969300c8e4b39a5534da959"
route = ""
workers_dev = true

# KV Settings
kv_namespaces = [ 
  { binding = "WF_KV", id = "e319d3d184b74e67a277aca2bd12e08f", preview_id = "b4955877edf74f65a774578f0dba939a" }
]

[env.prod]
name = "weddingflare-api"
zone_id = "6742fb7575e78ff485737fbab12254af"
route = "weddingflare.carsonseese.com/api/*"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
