name = "eventflare-api-dev"

# Build Configuration
type = "javascript"
compatibility_date = "2021-10-04"

# Account Settings
account_id = "257d9994d1e15e8fbeb6053f590ad96b"
zone_id = "60e63062a969300c8e4b39a5534da959"
route = ""
workers_dev = true

# KV Settings
kv_namespaces = [ 
  { binding = "EF_KV", id = "5f20b350e7334a74a948610d18c7e1bd", preview_id = "726ac3b7103841c386018cf19584e48f" }
]

[env.production]
name = "eventflare-api"
zone_id = "6742fb7575e78ff485737fbab12254af"
route = "eventflare.carsonseese.com/api/*"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
