name: Deploy Application

on:
  push:
    tags:
      - "*" # Push events to every tag not containing /
jobs:
  deploy-api:
    runs-on: ubuntu-latest
    name: Deploy API
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
          workingDirectory: "packages/api"

  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.CF_PAGES_HOOK }}
          method: "POST"
